"""
Automated health monitoring system for Dell PowerEdge servers.
Runs periodic health checks and triggers alerts based on thresholds.
"""

import asyncio
import logging
from typing import Dict, List, Any, Optional, Callable
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
import json

from core.health_scorer import HealthScorer, HealthLevel
from core.webhook_manager import webhook_manager, WebhookEvent
from core.predictive_analytics import predictive_analytics
from core.cache_manager import cache_manager

logger = logging.getLogger(__name__)

class MonitorStatus(Enum):
    ACTIVE = "active"
    PAUSED = "paused"
    STOPPED = "stopped"
    ERROR = "error"

class AlertSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"

@dataclass
class HealthCheck:
    """Individual health check configuration"""
    name: str
    interval_seconds: int
    enabled: bool = True
    threshold_warning: Optional[float] = None
    threshold_critical: Optional[float] = None
    last_run: Optional[datetime] = None
    last_result: Optional[Dict[str, Any]] = None
    consecutive_failures: int = 0
    
@dataclass
class HealthAlert:
    """Health alert generated by monitoring system"""
    id: str
    timestamp: datetime
    severity: AlertSeverity
    component: str
    message: str
    data: Dict[str, Any]
    acknowledged: bool = False
    acknowledged_by: Optional[str] = None
    acknowledged_at: Optional[datetime] = None

class HealthMonitor:
    """Automated health monitoring system"""
    
    def __init__(self):
        self.status = MonitorStatus.STOPPED
        self.checks: Dict[str, HealthCheck] = {}
        self.alerts: List[HealthAlert] = []
        self.monitoring_task: Optional[asyncio.Task] = None
        self.server_info: Dict[str, Any] = {}
        self.redfish_client = None
        
        # Alert callbacks
        self.alert_callbacks: List[Callable[[HealthAlert], None]] = []
        
        # Setup default health checks
        self._setup_default_checks()
    
    def _setup_default_checks(self):
        """Setup default health checks"""
        self.checks = {
            "temperature": HealthCheck(
                name="Temperature Monitoring",
                interval_seconds=60,  # Every minute
                threshold_warning=75.0,
                threshold_critical=85.0
            ),
            "power": HealthCheck(
                name="Power Supply Monitoring",
                interval_seconds=120,  # Every 2 minutes
                threshold_warning=0.80,
                threshold_critical=0.70
            ),
            "memory": HealthCheck(
                name="Memory Health Monitoring",
                interval_seconds=300,  # Every 5 minutes
            ),
            "storage": HealthCheck(
                name="Storage Health Monitoring",
                interval_seconds=300,  # Every 5 minutes
            ),
            "overall_health": HealthCheck(
                name="Overall Health Score",
                interval_seconds=300,  # Every 5 minutes
                threshold_warning=70.0,
                threshold_critical=50.0
            )
        }
    
    def set_server_info(self, server_info: Dict[str, Any], redfish_client):
        """Set server information and Redfish client"""
        self.server_info = server_info
        self.redfish_client = redfish_client
    
    def add_alert_callback(self, callback: Callable[[HealthAlert], None]):
        """Add callback for alert notifications"""
        self.alert_callbacks.append(callback)
    
    async def start_monitoring(self):
        """Start health monitoring"""
        if self.status == MonitorStatus.ACTIVE:
            logger.warning("Health monitoring is already active")
            return
        
        if not self.redfish_client:
            logger.error("Cannot start monitoring: No Redfish client available")
            return
        
        self.status = MonitorStatus.ACTIVE
        self.monitoring_task = asyncio.create_task(self._monitoring_loop())
        logger.info("Health monitoring started")
    
    async def stop_monitoring(self):
        """Stop health monitoring"""
        if self.status != MonitorStatus.ACTIVE:
            return
        
        self.status = MonitorStatus.STOPPED
        
        if self.monitoring_task:
            self.monitoring_task.cancel()
            try:
                await self.monitoring_task
            except asyncio.CancelledError:
                pass
        
        logger.info("Health monitoring stopped")
    
    async def pause_monitoring(self):
        """Pause health monitoring"""
        if self.status == MonitorStatus.ACTIVE:
            self.status = MonitorStatus.PAUSED
            logger.info("Health monitoring paused")
    
    async def resume_monitoring(self):
        """Resume health monitoring"""
        if self.status == MonitorStatus.PAUSED:
            self.status = MonitorStatus.ACTIVE
            logger.info("Health monitoring resumed")
    
    async def _monitoring_loop(self):
        """Main monitoring loop"""
        logger.info("Health monitoring loop started")
        
        try:
            while self.status == MonitorStatus.ACTIVE:
                start_time = datetime.utcnow()
                
                # Run all enabled checks
                for check_name, check in self.checks.items():
                    if not check.enabled:
                        continue
                    
                    # Check if it's time to run this check
                    if (check.last_run is None or 
                        (start_time - check.last_run).total_seconds() >= check.interval_seconds):
                        
                        try:
                            await self._run_health_check(check_name, check)
                        except Exception as e:
                            logger.error(f"Health check {check_name} failed: {str(e)}")
                            check.consecutive_failures += 1
                            
                            # Create alert if too many failures
                            if check.consecutive_failures >= 3:
                                await self._create_alert(
                                    AlertSeverity.CRITICAL,
                                    "monitoring",
                                    f"Health check {check_name} failed {check.consecutive_failures} times",
                                    {"check_name": check_name, "error": str(e)}
                                )
                
                # Sleep until next check cycle
                elapsed = (datetime.utcnow() - start_time).total_seconds()
                sleep_time = max(10, 30 - elapsed)  # Check every 30 seconds minimum
                await asyncio.sleep(sleep_time)
                
        except asyncio.CancelledError:
            logger.info("Health monitoring loop cancelled")
        except Exception as e:
            logger.error(f"Health monitoring loop error: {str(e)}")
            self.status = MonitorStatus.ERROR
    
    async def _run_health_check(self, check_name: str, check: HealthCheck):
        """Run a single health check"""
        logger.debug(f"Running health check: {check_name}")
        
        try:
            if check_name == "temperature":
                result = await self._check_temperature(check)
            elif check_name == "power":
                result = await self._check_power(check)
            elif check_name == "memory":
                result = await self._check_memory(check)
            elif check_name == "storage":
                result = await self._check_storage(check)
            elif check_name == "overall_health":
                result = await self._check_overall_health(check)
            else:
                logger.warning(f"Unknown health check: {check_name}")
                return
            
            check.last_run = datetime.utcnow()
            check.last_result = result
            check.consecutive_failures = 0
            
            # Check thresholds and create alerts if needed
            await self._check_thresholds(check_name, check, result)
            
        except Exception as e:
            logger.error(f"Health check {check_name} error: {str(e)}")
            raise
    
    async def _check_temperature(self, check: HealthCheck) -> Dict[str, Any]:
        """Check temperature sensors"""
        if not self.redfish_client:
            raise RuntimeError("No Redfish client available")
        
        thermal_data = await self.redfish_client.get_temperature_sensors()
        
        if not thermal_data or "Temperatures" not in thermal_data:
            raise RuntimeError("Failed to get temperature data")
        
        temps = thermal_data["Temperatures"]
        max_temp = max(t.get("ReadingCelsius", 0) for t in temps)
        avg_temp = sum(t.get("ReadingCelsius", 0) for t in temps) / len(temps) if temps else 0
        
        return {
            "max_temperature": max_temp,
            "avg_temperature": avg_temp,
            "sensor_count": len(temps),
            "sensors": temps
        }
    
    async def _check_power(self, check: HealthCheck) -> Dict[str, Any]:
        """Check power supplies"""
        if not self.redfish_client:
            raise RuntimeError("No Redfish client available")
        
        power_data = await self.redfish_client.get_power_supplies()
        
        if not power_data or "PowerSupplies" not in power_data:
            raise RuntimeError("Failed to get power data")
        
        psus = power_data["PowerSupplies"]
        healthy_psus = sum(1 for psu in psus if psu.get("Status", {}).get("Health") == "OK")
        total_power = sum(psu.get("OutputWatts", 0) for psu in psus)
        capacity_power = sum(psu.get("CapacityWatts", 1) for psu in psus)
        efficiency = total_power / capacity_power if capacity_power > 0 else 0
        
        return {
            "healthy_psus": healthy_psus,
            "total_psus": len(psus),
            "efficiency": efficiency,
            "total_output_watts": total_power,
            "capacity_watts": capacity_power
        }
    
    async def _check_memory(self, check: HealthCheck) -> Dict[str, Any]:
        """Check memory health"""
        if not self.redfish_client:
            raise RuntimeError("No Redfish client available")
        
        memory_data = await self.redfish_client.get_memory()
        
        if not memory_data or "Memory" not in memory_data:
            raise RuntimeError("Failed to get memory data")
        
        dimms = memory_data["Memory"]
        healthy_dimms = sum(1 for dimm in dimms if dimm.get("Status", {}).get("Health") == "OK")
        total_capacity = sum(dimm.get("CapacityMiB", 0) for dimm in dimms)
        
        # Check for ECC errors
        ecc_errors = 0
        for dimm in dimms:
            ecc_data = dimm.get("Oem", {}).get("Dell", {}).get("DellMemory", {})
            ecc_errors += ecc_data.get("CorrectableEccErrors", 0)
            ecc_errors += ecc_data.get("UncorrectableEccErrors", 0)
        
        return {
            "healthy_dimms": healthy_dimms,
            "total_dimms": len(dimms),
            "total_capacity_mb": total_capacity,
            "ecc_errors": ecc_errors
        }
    
    async def _check_storage(self, check: HealthCheck) -> Dict[str, Any]:
        """Check storage health"""
        if not self.redfish_client:
            raise RuntimeError("No Redfish client available")
        
        storage_data = await self.redfish_client.get_storage_devices()
        
        if not storage_data:
            raise RuntimeError("Failed to get storage data")
        
        # Simplified storage health check
        drives = storage_data.get("drives", [])
        healthy_drives = sum(1 for drive in drives if drive.get("Status", {}).get("Health") == "OK")
        total_capacity = sum(drive.get("CapacityBytes", 0) for drive in drives)
        
        return {
            "healthy_drives": healthy_drives,
            "total_drives": len(drives),
            "total_capacity_bytes": total_capacity
        }
    
    async def _check_overall_health(self, check: HealthCheck) -> Dict[str, Any]:
        """Check overall health score"""
        if not self.redfish_client:
            raise RuntimeError("No Redfish client available")
        
        # Collect data from all subsystems
        subsystem_data = {}
        
        try:
            thermal = await self.redfish_client.get_temperature_sensors()
            if thermal:
                subsystem_data["thermal"] = thermal
        except:
            pass
        
        try:
            power = await self.redfish_client.get_power_supplies()
            if power:
                subsystem_data["power"] = power
        except:
            pass
        
        try:
            memory = await self.redfish_client.get_memory()
            if memory:
                subsystem_data["memory"] = memory
        except:
            pass
        
        # Calculate health score
        health_result = health_scorer.calculate_overall_health(subsystem_data)
        
        return health_result
    
    async def _check_thresholds(self, check_name: str, check: HealthCheck, result: Dict[str, Any]):
        """Check thresholds and create alerts"""
        if check_name == "temperature":
            max_temp = result.get("max_temperature", 0)
            if max_temp >= check.threshold_critical:
                await self._create_alert(
                    AlertSeverity.CRITICAL,
                    "thermal",
                    f"Critical temperature detected: {max_temp}°C",
                    {"max_temperature": max_temp, "threshold": check.threshold_critical}
                )
            elif max_temp >= check.threshold_warning:
                await self._create_alert(
                    AlertSeverity.WARNING,
                    "thermal",
                    f"High temperature detected: {max_temp}°C",
                    {"max_temperature": max_temp, "threshold": check.threshold_warning}
                )
        
        elif check_name == "power":
            efficiency = result.get("efficiency", 1.0)
            if efficiency <= check.threshold_critical:
                await self._create_alert(
                    AlertSeverity.CRITICAL,
                    "power",
                    f"Critical power efficiency: {efficiency:.1%}",
                    {"efficiency": efficiency, "threshold": check.threshold_critical}
                )
            elif efficiency <= check.threshold_warning:
                await self._create_alert(
                    AlertSeverity.WARNING,
                    "power",
                    f"Low power efficiency: {efficiency:.1%}",
                    {"efficiency": efficiency, "threshold": check.threshold_warning}
                )
        
        elif check_name == "overall_health":
            overall_score = result.get("overall_score", 100)
            if overall_score <= check.threshold_critical:
                await self._create_alert(
                    AlertSeverity.CRITICAL,
                    "system",
                    f"Critical system health score: {overall_score}",
                    {"health_score": overall_score, "threshold": check.threshold_critical}
                )
            elif overall_score <= check.threshold_warning:
                await self._create_alert(
                    AlertSeverity.WARNING,
                    "system",
                    f"Low system health score: {overall_score}",
                    {"health_score": overall_score, "threshold": check.threshold_warning}
                )
    
    async def _create_alert(self, severity: AlertSeverity, component: str, message: str, data: Dict[str, Any]):
        """Create and process a health alert"""
        alert_id = f"{component}_{int(datetime.utcnow().timestamp())}"
        
        alert = HealthAlert(
            id=alert_id,
            timestamp=datetime.utcnow(),
            severity=severity,
            component=component,
            message=message,
            data=data
        )
        
        self.alerts.append(alert)
        
        # Keep only last 1000 alerts
        if len(self.alerts) > 1000:
            self.alerts = self.alerts[-1000:]
        
        logger.warning(f"Health alert created: {severity.value.upper()} - {message}")
        
        # Trigger webhook
        webhook_event = WebhookEvent.HEALTH_CRITICAL if severity == AlertSeverity.CRITICAL else WebhookEvent.HEALTH_WARNING
        await webhook_manager.trigger_event(
            webhook_event,
            self.server_info,
            data,
            severity.value
        )
        
        # Call alert callbacks
        for callback in self.alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Alert callback error: {str(e)}")
    
    def acknowledge_alert(self, alert_id: str, acknowledged_by: str) -> bool:
        """Acknowledge an alert"""
        for alert in self.alerts:
            if alert.id == alert_id and not alert.acknowledged:
                alert.acknowledged = True
                alert.acknowledged_by = acknowledged_by
                alert.acknowledged_at = datetime.utcnow()
                logger.info(f"Alert {alert_id} acknowledged by {acknowledged_by}")
                return True
        return False
    
    def get_active_alerts(self, severity: Optional[AlertSeverity] = None) -> List[HealthAlert]:
        """Get active (unacknowledged) alerts"""
        alerts = [a for a in self.alerts if not a.acknowledged]
        
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        
        # Sort by timestamp (newest first)
        alerts.sort(key=lambda a: a.timestamp, reverse=True)
        return alerts
    
    def get_alert_summary(self) -> Dict[str, Any]:
        """Get alert summary statistics"""
        total_alerts = len(self.alerts)
        active_alerts = len(self.get_active_alerts())
        
        severity_counts = {}
        for severity in AlertSeverity:
            severity_counts[severity.value] = len(self.get_active_alerts(severity))
        
        return {
            "total_alerts": total_alerts,
            "active_alerts": active_alerts,
            "severity_breakdown": severity_counts,
            "monitoring_status": self.status.value,
            "enabled_checks": len([c for c in self.checks.values() if c.enabled])
        }
    
    def get_monitoring_status(self) -> Dict[str, Any]:
        """Get detailed monitoring status"""
        return {
            "status": self.status.value,
            "checks": [
                {
                    "name": check.name,
                    "enabled": check.enabled,
                    "interval_seconds": check.interval_seconds,
                    "last_run": check.last_run.isoformat() if check.last_run else None,
                    "consecutive_failures": check.consecutive_failures,
                    "threshold_warning": check.threshold_warning,
                    "threshold_critical": check.threshold_critical
                }
                for check in self.checks.values()
            ],
            "alert_summary": self.get_alert_summary()
        }

# Global health monitor instance
health_monitor = HealthMonitor()
